        
- hosts: webservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: maven clean package
      command: mvn clean package
      args:
        chdir: /home/sysadmin/CI-AnsibleJenkins
    
    - name: copy war file
      copy: 
        src: ./target/LoginWebApp-1.war 
        dest: /var/lib/tomcat9/webapps
    
    - name: restart tomcat
      service:
       name: tomcat9
       state: restarted