        
- hosts: webservers
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: copy war file
      copy: 
        src: ./target/LoginWebApp-1.war 
        dest: /opt/apache-tomcat/webapps/
    
    # - name: restart tomcat
    #   service:
    #    name: tomcat
    #    state: restarted
      
    - name: restart tomcat
      copy: 
        src: ./target/LoginWebApp-1.war 
        dest: /opt/apache-tomcat/webapps/      