        
- hosts: CI
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: maven clean package
      command: mvn clean package
      args:
       chdir: /var/lib/jenkins/workspace/Deploy_JavaApp_Test/

- hosts: webservers
  become: true
  become_user: root
  gather_facts: true
  warn: false
  tasks:    
    - name: copy war file
      copy: 
        src: ./target/LoginWebApp-1.war 
        dest: /var/lib/tomcat9/webapps
      
    - name: stop tomcat
      command: service tomcat9 stop

    - name: start tomcat
      command: service tomcat9 start

       