        
- hosts: webservers
  become: true
  become_user: root
  gather_facts: false
  tasks:
    # - include_role:
    #     name: tomcat
    - name: copy war file
      copy: 
        src: ./target/LoginWebApp-1.war 
        dest: /opt/apache-tomcat/webapps/

    - name: Restart Tomcat service
      copy: 
        src: ./target/LoginWebApp-1.war 
        dest: /opt/apache-tomcat/webapps/
    
    # - name: restart tomcat
    #   service:
    #    name: tomcat
    #    state: restarted

    # - name: Copy tomcat service file
    #   template:
    #     src: templates/tomcat.service.j2
    #     dest: /etc/systemd/system/tomcat.service
    #   when: ansible_service_mgr == "systemd"

    # - name: Start and enable tomcat
    #   service:
    #     daemon_reload: yes
    #     name: tomcat
    #     state: started
    #     enabled: yes
    #   when: ansible_service_mgr == "systemd"
    
    # - name: Set UI access credentials
    #   template:
    #     src: tomcat-users.xml.j2
    #     dest: /usr/share/tomcat/conf/tomcat-users.xml
    #   notify: restart tomcat

      