---
  
  - name: copy war file
    copy: src=./target/LoginWebApp-1.war dest=/opt/apache-tomcat/webapps/


  - name: Restart Tomcat service
    systemd:
      name: tomcat
      state: restarted
      enabled: true
      daemon_reload: true

