---
  
- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/opt/apache-tomcat/webapps/

- name: Stop Tomcat service
  systemd:
   name: tomcat
   state: stopped
   enabled: true
   daemon_reload: true

- name: Start Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true