---
  
- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/opt/apache-tomcat/webapps/

- name: Start Tomcat service
  systemd:
    name: tomcat9
    state: started
    enabled: true
    daemon_reload: true